services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: resume_db1
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_broker
    ports:
      - "6380:6379"

  fastapi:
    build: .
    image : fastapi_app
    environment:
      - PYTHONPATH=/app
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  celery:
    build: .
    image : celery_worker
    container_name: celery_worker
    command: celery -A app.workers.celery_app.celery_app worker --loglevel=info
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  pgdata:
