"""add extracted_text to jobs

Revision ID: 7344b90c5e03
Revises: fe7977ee3781
Create Date: 2026-03-05 13:16:36.641670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7344b90c5e03'
down_revision: Union[str, Sequence[str], None] = 'fe7977ee3781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'extracted_text')
    # ### end Alembic commands ###
