"""add resume file fields to jobs

Revision ID: fe7977ee3781
Revises: d662fe7523d7
Create Date: 2026-03-02 12:07:17.012748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7977ee3781'
down_revision: Union[str, Sequence[str], None] = 'd662fe7523d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('stored_path', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('content_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'content_type')
    op.drop_column('jobs', 'stored_path')
    op.drop_column('jobs', 'original_filename')
    # ### end Alembic commands ###
